#!/usr/bin/env bash
#
# Native Termux installer for the Hermes commerce control plane.
#
# What it does, in order:
#
#   1. resolves absolute package and repository paths from its own location, so
#      it works from any working directory;
#   2. installs exact locked dependencies and compiles;
#   3. creates ~/.hermes/commerce-control/ with a stable MCP wrapper;
#   4. runs the doctor and refuses to register an unhealthy install;
#   5. inspects the local `hermes mcp` surface and registers ONLY the unified
#      commerce-control MCP using the supported native syntax;
#   6. verifies the registration and asserts that no live-action tool exists.
#
# What it deliberately does NOT do:
#
#   - it never writes a wallet, private key, mnemonic, seed phrase, NWC URI or
#     any other financial signing value into the Hermes configuration;
#   - it never enables EXTERNAL_WRITES_ENABLED or LIVE_VALUE_MOVEMENT_ENABLED;
#   - it registers exactly one MCP server, not a family of them;
#   - it edits the Hermes configuration file directly only if the supported CLI
#     path is unavailable, and takes a timestamped backup first.
#
# The generated wrapper actively scrubs wallet-secret-shaped variables from the
# environment it hands to the server. That matters because Hermes launches the
# process: without the scrub, a key sitting in the operator's shell would be
# visible to the control plane, and the Mode-A claim "no signer is reachable"
# would depend on the operator's shell hygiene rather than on this code.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${PACKAGE_ROOT}/../.." && pwd)"

HERMES_HOME="${HERMES_HOME:-${HOME}/.hermes}"
INSTALL_DIR="${HERMES_HOME}/commerce-control"
WRAPPER="${INSTALL_DIR}/commerce-control-mcp.sh"
STATE_ROOT="${INSTALL_DIR}/state"
LOG_FILE="${INSTALL_DIR}/install.log"
MCP_NAME="commerce-control"

SKIP_DEPS=0
SKIP_REGISTER=0
FORCE_REREGISTER=0

usage() {
  cat <<'USAGE'
Usage: install-hermes-commerce-control.sh [options]

  --skip-deps        do not run "npm ci" (use the tree already installed)
  --skip-register    install and verify locally, but do not touch Hermes
  --force            remove and re-add an existing commerce-control MCP entry
  -h, --help         show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-deps) SKIP_DEPS=1 ;;
    --skip-register) SKIP_REGISTER=1 ;;
    --force) FORCE_REREGISTER=1 ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

log() { printf '[install] %s\n' "$*"; }
fail() { printf '[install] ERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- preflight

log "package root: ${PACKAGE_ROOT}"
log "repository root: ${REPO_ROOT}"

command -v node >/dev/null 2>&1 || fail "node is not on PATH"
command -v npm >/dev/null 2>&1 || fail "npm is not on PATH"

NODE_VERSION="$(node -p 'process.versions.node')"
NODE_MAJOR="${NODE_VERSION%%.*}"
[[ "${NODE_MAJOR}" == "24" ]] || fail "Node 24 is required for built-in node:sqlite; found ${NODE_VERSION}"
log "node ${NODE_VERSION}"

node -e 'import("node:sqlite").then(m=>{if(typeof m.DatabaseSync!=="function")process.exit(1)}).catch(()=>process.exit(1))' \
  || fail "built-in node:sqlite is unavailable on this runtime"
log "built-in node:sqlite available"

# ------------------------------------------------------- dependencies + build

cd "${PACKAGE_ROOT}"

if [[ "${SKIP_DEPS}" -eq 0 ]]; then
  [[ -f package-lock.json ]] || fail "package-lock.json is missing; refusing to install unlocked dependencies"
  log "installing exact locked dependencies (npm ci)"
  npm ci
else
  log "skipping npm ci by request"
fi

log "compiling TypeScript"
npm run build

CLI_ENTRY="${PACKAGE_ROOT}/dist/cli.js"
MCP_ENTRY="${PACKAGE_ROOT}/dist/mcp/server.js"
[[ -f "${CLI_ENTRY}" ]] || fail "build did not produce ${CLI_ENTRY}"
[[ -f "${MCP_ENTRY}" ]] || fail "build did not produce ${MCP_ENTRY}"
log "compiled entrypoints present"

# ------------------------------------------------------------- install layout

mkdir -p "${INSTALL_DIR}" "${STATE_ROOT}"
log "install directory: ${INSTALL_DIR}"

CLI_WRAPPER="${INSTALL_DIR}/commerce-control-cli.sh"

# Both wrappers share one prologue so the CLI the operator runs and the server
# Hermes launches see byte-for-byte the same environment.
write_wrapper() {
  local target_path="$1" entry="$2" title="$3"
  cat > "${target_path}" <<WRAPPER_EOF
#!/usr/bin/env bash
#
# ${title}
# Generated by install-hermes-commerce-control.sh — regenerate rather than edit.
#
# Mode A is asserted here as well as in the compiled configuration loader, so a
# stray environment variable cannot flip an activation gate.

set -euo pipefail

# Remove any wallet or financial-signing secret inherited from the launching
# environment. The control plane must not be able to see spending authority even
# if the operator's shell exports it, so the Mode-A claim does not depend on
# shell hygiene.
for _name in \$(compgen -e); do
  case "\${_name^^}" in
    *PRIVATE_KEY*|*PRIVATEKEY*|*MNEMONIC*|*SEED_PHRASE*|*SEEDPHRASE*|*WALLET_SECRET*|*SIGNING_KEY*|*KEYSTORE*|*XPRV*|*NWC*)
      unset "\${_name}"
      ;;
  esac
done
unset _name

export COMMERCE_MODE=A
export EXTERNAL_WRITES_ENABLED=false
export LIVE_VALUE_MOVEMENT_ENABLED=false
export COMMERCE_STATE_ROOT="${STATE_ROOT}"
export COMMERCE_REPO_ROOT="${REPO_ROOT}"

exec node "${entry}" "\$@"
WRAPPER_EOF
  chmod 0755 "${target_path}"
}

write_wrapper "${WRAPPER}" "${MCP_ENTRY}" "Stable Hermes MCP entrypoint for the commerce control plane."
write_wrapper "${CLI_WRAPPER}" "${CLI_ENTRY}" "Stable CLI entrypoint for the commerce control plane."
log "wrote MCP wrapper: ${WRAPPER}"
log "wrote CLI wrapper: ${CLI_WRAPPER}"

# ------------------------------------------------- wallet-secret scrub proof

# The doctor exits non-zero when it is unhealthy, which is the correct
# behaviour, so these checks capture output first rather than piping under
# `set -o pipefail`.

read_wallet_flag() {
  # Prints "true"/"false"/"error" for the doctor's walletSecretPresent field.
  printf '%s' "$1" | node -e '
    let s = "";
    process.stdin.on("data", (d) => { s += d; }).on("end", () => {
      try {
        const doc = JSON.parse(s);
        process.stdout.write(String(doc.data.walletSecretPresent));
      } catch {
        process.stdout.write("error");
      }
    });
  '
}

UNSCRUBBED_JSON="$(
  PIPRAIL_PRIVATE_KEY=canary-not-a-real-key \
  COMMERCE_STATE_ROOT="${STATE_ROOT}" COMMERCE_REPO_ROOT="${REPO_ROOT}" \
  node "${CLI_ENTRY}" doctor --json 2>/dev/null || true
)"
if [[ "$(read_wallet_flag "${UNSCRUBBED_JSON}")" != "true" ]]; then
  fail "the doctor did not detect a wallet variable; the secret check is not working"
fi
log "confirmed: an unscrubbed wallet variable IS detected"

SCRUBBED_JSON="$(
  PIPRAIL_PRIVATE_KEY=canary-not-a-real-key "${CLI_WRAPPER}" doctor --json 2>/dev/null || true
)"
if [[ "$(read_wallet_flag "${SCRUBBED_JSON}")" != "false" ]]; then
  fail "the wrapper did not scrub a wallet variable out of the launch environment"
fi
log "confirmed: the wrapper scrubs a wallet variable before starting the process"

# ------------------------------------------------------------------- doctor

log "running doctor through the installed wrapper"
DOCTOR_JSON="$("${CLI_WRAPPER}" doctor --json 2>/dev/null || true)"

printf '%s' "${DOCTOR_JSON}" | node -e '
let s = "";
process.stdin.on("data", (d) => { s += d; }).on("end", () => {
  let doc;
  try { doc = JSON.parse(s); } catch {
    process.stderr.write("[install] ERROR: doctor produced no parseable JSON\n");
    process.exit(1);
  }
  const data = doc.data ?? {};
  for (const check of data.checks ?? []) {
    process.stderr.write(`[install]   ${check.status.toUpperCase().padEnd(4)} ${check.id}\n`);
  }
  if (data.mode !== "A") { process.stderr.write("[install] ERROR: mode is not A\n"); process.exit(1); }
  if (data.externalWritesEnabled !== false) { process.stderr.write("[install] ERROR: external writes enabled\n"); process.exit(1); }
  if (data.liveValueMovementEnabled !== false) { process.stderr.write("[install] ERROR: live value movement enabled\n"); process.exit(1); }
  if (data.walletSecretPresent !== false) { process.stderr.write("[install] ERROR: a wallet secret is present\n"); process.exit(1); }
  if (doc.ok !== true) { process.stderr.write("[install] ERROR: doctor reported an unhealthy install\n"); process.exit(1); }
});
' || fail "doctor refused this installation; not registering with Hermes"
log "doctor healthy: mode A, both gates false, no wallet secret"

# --------------------------------------------------------- local MCP handshake

log "verifying the MCP entrypoint answers a stdio handshake"
HANDSHAKE_OUT="$(
  printf '%s\n%s\n%s\n' \
    '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"installer","version":"1.0.0"}}}' \
    '{"jsonrpc":"2.0","method":"notifications/initialized"}' \
    '{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}' \
    | "${WRAPPER}" 2>/dev/null
)"

printf '%s' "${HANDSHAKE_OUT}" | node -e '
const EXPECTED = [
  "commerce_discover_services","commerce_discover_work","commerce_export_evidence",
  "commerce_inspect","commerce_prepare_claim","commerce_prepare_publish",
  "commerce_prepare_purchase","commerce_probe","commerce_quote","commerce_sources",
  "commerce_status",
].sort();
const FORBIDDEN = [
  "commerce_pay","commerce_purchase","commerce_claim","commerce_submit","commerce_settle",
  "commerce_transfer","commerce_withdraw","commerce_fund","commerce_publish",
  "piprail_pay_request","pay","purchase","claim","submit","settle","transfer","withdraw","publish",
];
let s = "";
process.stdin.on("data", (d) => { s += d; }).on("end", () => {
  const lines = s.split("\n").filter((l) => l.trim() !== "");
  for (const line of lines) {
    // stdout must be MCP protocol only.
    const msg = JSON.parse(line);
    if (msg.jsonrpc !== "2.0") { process.stderr.write("[install] ERROR: non-protocol stdout\n"); process.exit(1); }
  }
  const listed = lines.map((l) => JSON.parse(l)).find((m) => m.id === 2);
  const names = (listed?.result?.tools ?? []).map((t) => t.name).sort();
  if (JSON.stringify(names) !== JSON.stringify(EXPECTED)) {
    process.stderr.write(`[install] ERROR: unexpected tool set: ${names.join(",")}\n`);
    process.exit(1);
  }
  for (const bad of FORBIDDEN) {
    if (names.includes(bad)) { process.stderr.write(`[install] ERROR: forbidden tool ${bad}\n`); process.exit(1); }
  }
  process.stderr.write(`[install]   ${names.length} tools, no live-action tool present\n`);
});
' || fail "the MCP entrypoint did not expose the expected safe tool set"
log "MCP handshake verified"

# --------------------------------------------------------- Hermes registration

if [[ "${SKIP_REGISTER}" -eq 1 ]]; then
  log "skipping Hermes registration by request"
else
  if ! command -v hermes >/dev/null 2>&1; then
    log "WARNING: hermes is not on PATH; skipping registration (degraded)"
  else
    export HERMES_NONINTERACTIVE=1
    HERMES_VERSION="$(hermes --version 2>&1 | head -1 || true)"
    log "hermes: ${HERMES_VERSION}"

    # Inspect the supported surface before using it, rather than assuming.
    MCP_HELP="$(hermes mcp --help 2>&1 || true)"
    printf '%s' "${MCP_HELP}" | grep -q ' add ' \
      || fail "this Hermes build does not support 'hermes mcp add'"
    if printf '%s' "${MCP_HELP}" | grep -q -- '--command'; then
      : # stdio registration supported
    elif hermes mcp add --help 2>&1 | grep -q -- '--command'; then
      :
    else
      fail "this Hermes build does not support stdio MCP registration via --command"
    fi
    log "hermes mcp add --command is supported"

    EXISTING="$(hermes mcp list 2>&1 || true)"
    if printf '%s' "${EXISTING}" | grep -q "${MCP_NAME}"; then
      if [[ "${FORCE_REREGISTER}" -eq 1 ]]; then
        log "removing existing ${MCP_NAME} entry"
        hermes mcp remove "${MCP_NAME}" || log "WARNING: remove reported a problem"
      else
        log "${MCP_NAME} is already registered; pass --force to re-register"
      fi
    fi

    if ! hermes mcp list 2>&1 | grep -q "${MCP_NAME}"; then
      log "registering ${MCP_NAME} (stdio, no credentials)"
      # Only the wrapper path is passed. No --env is used, so no value of any
      # kind is written into the Hermes configuration.
      if hermes mcp add "${MCP_NAME}" --command "${WRAPPER}" --connect-timeout 90; then
        log "registered ${MCP_NAME}"
      else
        log "WARNING: 'hermes mcp add' failed; the local install is still valid (degraded)"
      fi
    fi

    log "hermes mcp list:"
    hermes mcp list 2>&1 | sed 's/^/[install]   /' || true

    if hermes mcp list 2>&1 | grep -q "${MCP_NAME}"; then
      log "verifying the registered server responds"
      hermes mcp test "${MCP_NAME}" 2>&1 | sed 's/^/[install]   /' || log "WARNING: 'hermes mcp test' reported a problem"
    fi
  fi
fi

# ------------------------------------------------------------------- summary

{
  printf 'installed_at=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'package_root=%s\n' "${PACKAGE_ROOT}"
  printf 'repo_root=%s\n' "${REPO_ROOT}"
  printf 'wrapper=%s\n' "${WRAPPER}"
  printf 'cli_wrapper=%s\n' "${CLI_WRAPPER}"
  printf 'state_root=%s\n' "${STATE_ROOT}"
  printf 'node=%s\n' "${NODE_VERSION}"
  printf 'mcp_name=%s\n' "${MCP_NAME}"
  printf 'mode=A external_writes=false live_value_movement=false wallet_secret=false\n'
} >> "${LOG_FILE}"

log "done. Log: ${LOG_FILE}"
log "CLI:  node ${CLI_ENTRY} status --json"
log "MCP:  ${WRAPPER}"
